import { useState, createContext, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  id: {
    // General Translate
    Senin: "Sen",
    Selasa: "Sel",
    Rabu: "Rab",
    Kamis: "Kam",
    Jumat: "Jum",
    Sabtu: "Sab",
    Minggu: "Ming",
    // General
    HourText: "jam",
    LowText: "Rendah",
    MediumText: "Sedang",
    HighText: "Tinggi",
    DeadlinePressureTitle: "Tekanan Deadline",
    PhysicalActivityTitle: "Aktivitas Fisik",
    MoodScoreTitle: "Skor Suasana Hati",
    FatigueLevelTitle: "Tingkat Kelelahan",
    ModerateText: "Sedang", // Added for stress_level translation
    NewInsight: "Rekomendasi untuk Anda",
    CloseButton: "Tutup",
    DashboardDateLocale: "id-ID",
    MinuteText: "Mnt",
    PriorityTodayTitle: "Rekomendasi Aktivitas",
    LongTermTitle: "Saran Jangka Panjang",

    // LeftPanel
    Heading1: "Analisis Tingkat Stres Berbasis AI",
    Heading2: "Untuk Kesehatan Mental Anda.",
    Deskripsi: "Pantau kondisi mental Anda melalui evaluasi aktivitas dan kebiasaan harian menggunakan teknologi Artificial Intelligence secara real-time.",
    Subheading1: "Cek Stress Harian",
    Subdeskripsi1: "AI menganalisis jawaban questionnaire harian untuk memperkirakan tingkat stres secara cepat dan akurat.",
    Subheading2: "Laporan & Insight Personal",
    Subdeskripsi2: "Dapatkan ringkasan kondisi stres serta rekomendasi harian untuk membantu menjaga kesehatan mental Anda",

    // Register Pages
    Create: "Buat Akun",
    Form: "Silakan lengkapi formulir di bawah ini.",
    LabelName: "Nama Lengkap",
    InputName: "Masukan Nama Anda",
    InputEmail: "Masukan Email Anda",
    LabelPassword: "Kata Sandi",
    LabelConfirmPassword: "Konfirmasi Kata Sandi",
    SubmitRegister: "Daftar Sekarang",
    LabelLogin: "Sudah Punya Akun?",
    LinkLogin: "Masuk Di sini",
    Google: "Lanjut Dengan Google",

    // Login Pages
    Login: "Masuk",
    LabelRegister: "Belum punya akun?",
    LinkRegister: "Daftar",
    SubmitLogin: "Masuk Sekarang",
    ResetPassword: "Lupa Password",

    // Reset Password Pages
    HeadingResetPassword: "Lupa Kata Sandi?",
    DeskripsiResetPassword: "Masukkan email yang terdaftar untuk menerima instruksi reset kata sandi.",
    ButtonResetPassword: "Kirim Tautan Pemulih",
    BackToLogin: "Kembali ke Login",

    // New Password Pages
    HeadingNewPassword: "Buat Kata Sandi Baru",
    DeskripsiNewPassword: "Silakan masukkan kata sandi baru untuk akun Anda.",
    ButtonNewPassword: "Perbarui Kata Sandi",
    LabelNewPassword: "Kata Sandi Baru",
    LabelConfirmNewPassword: "Konfirmasi Kata Sandi Baru" ,

    // Sidebar
    ActSdbr: "Riwayat Aktivitas",
    CekStresSdbr: "Ringkasan",
    ReqomendationSdbr: "Rekomendasi",
    ProfileSdbr: "Profile Saya",
    StressCheck: "Cek Stres",
    LogoutSdbr: "Keluar",

    // Catat Aktivitas Pages
    ActivityPageTitle: "Input Data Aktivitas",
    LogActivityTitle: "Catat Data Aktivitas",
    ActivityPageDescription: "Lengkapi data di bawah untuk analisis tingkat stres yang lebih mendalam dari sistem AI kami.",
    ActivityDailySectionTitle: "Aktivitas Harian",
    ActivityDailySectionDescription: "Lengkapi data aktivitas Anda untuk mendapatkan prediksi stres yang lebih akurat.",
    ActivityDigitalSectionTitle: "Aktivitas Digital",
    ActivityDigitalSectionDescription: "Catat durasi penggunaan layar dan media sosial Anda.",
    ActivityConditionSectionTitle: "Kondisi Akademik & Personal",
    ActivityConditionSectionDescription: "Geser slider sesuai kondisi Anda kemarin.",
    ActivityDateTitle: "Tanggal Aktivitas",
    ActivitySleepHoursTitle: "Jam Tidur",
    ActivitySleepPlaceholder: "Contoh: 7.5",
    ActivitySleepDescription: "Total jam tidur semalam",
    ActivityPhysicalActivityPlaceholder: "Menit",
    ActivityPhysicalDescription: "Durasi aktivitas fisik",
    ActivityStudyHoursTitle: "Jam Belajar",
    ActivityStudyDescription: "Total waktu belajar di luar kelas",
    ActivityScreenTimeTitle: "Screen Time",
    ActivityScreenTimeDescription: "Total waktu layar di luar kebutuhan belajar",
    ActivitySocialMediaTitle: "Penggunaan Media Sosial",
    ActivitySocialMediaDescription: "Waktu di media sosial (Instagram, TikTok, X, dll.)",
    ActivityAssignmentLoadTitle: "Beban Tugas",
    ActivityAssignmentDescription: "Seberapa berat beban tugas Anda?",
    ActivityDeadlineDescription: "Seberapa mendesak deadline yang Anda hadapi?",
    ActivityFatigueDescription: "Seberapa lelah fisik dan mental yang Anda rasakan?",
    ActivityMoodDescription: "Bagaimana suasana hati Anda secara keseluruhan?",
    ActivitySelectDateLabel: "Pilih Tanggal Aktivitas",
    ActivitySubmitConfirmationTitle: "Kirim data aktivitas?",
    ActivitySubmitConfirmationDescription: "Apakah yakin ingin mengirim data aktivitas untuk tanggal",
    ActivityReviewAgainButton: "Periksa lagi",
    ActivityConfirmSubmitButton: "Ya, kirim",
    ActivityAllDatesFilledTitle: "Semua tanggal sudah terisi",
    ActivityAllDatesFilledDescription: "Empat tanggal aktivitas sebelum hari ini sudah memiliki catatan. Kamu akan diarahkan ke dashboard.",
    ActivityGoToDashboardButton: "Ke Dashboard",
    ActivityDateRequiredError: "Pilih tanggal aktivitas terlebih dahulu.",
    ActivityMinimumInputError: "Isi minimal satu data aktivitas sebelum simpan dan prediksi.",
    ActivityAnalysisLoadingTitle: "Menunggu hasil analisis AI...",
    ActivityAnalysisLoadingDescription: "Skor stres akan ditampilkan setelah model AI menyimpan hasil prediksi.",
    ActivityHoursSuffix: "JAM",
    ActivityMinutesSuffix: "MENIT",
    ActivityLowLabel: "Rendah",
    ActivityExtremeLabel: "Ekstrem",
    ActivityRelaxedLabel: "Santai",
    ActivityUrgentLabel: "Mendesak",
    ActivityFreshLabel: "Segar",
    ActivityExhaustedLabel: "Kelelahan Total",
    ActivityBadLabel: "Buruk",
    ActivityVeryGoodLabel: "Sangat Baik",
    ActivityQuiteHighStatus: "Cukup Tinggi",
    ActivityBadgeGood: "Baik",
    ActivityBadgeLow: "Rendah",
    ActivityBadgeMedium: "Sedang",
    ActivityBadgeQuiteHigh: "Cukup Tinggi",
    ActivityBadgeVeryGood: "Sangat Baik",
    ActivityBadgeVeryHigh: "Sangat Tinggi",
    ActivityDailyNoteTitle: "Catatan Harian",
    ActivityDailyNoteDescription: "Ceritakan secara singkat bagaimana hari Anda kemarin.",
    ActivityDailyNotePlaceholder: "Contoh: Hari ini saya merasa cukup lelah karena banyak tugas menumpuk, tidur kurang, dan sulit fokus saat belajar.",
    ActivitySubmitButton: "Simpan & Prediksi",
    ActivitySubmittingButton: "Menyimpan...",
    ActivitySaveDraftButton: "Simpan Draft",
    ActivityDraftSavedMessage: "Draft berhasil disimpan.",
    ActivitySuccessMessage: "Aktivitas berhasil dikirim.",
    ActivitySubmitErrorMessage: "Terjadi kesalahan saat mengirim data.",
    ActivityJournalHeader: "Jurnal Untuk Aktivitas Tanggal",
    ActivityJournalDescription: "Data ini akan digunakan untuk memprediksi skor stres, menghasilkan insight, dan rekomendasi.",
    ActivityReviewLabel: "Pratinjau Analisis",
    ActivityTodayStatusTitle: "Status Hari Ini",
    ActivityAnalysisTag: "Analisis",
    ActivityStressRiskHigh: "Risiko Stres Tinggi",
    ActivityGoToSummaryButton: "Ke Halaman Ringkasan",
    ActivityCloseButton: "Tutup",

    // Dashboard Pages
    HighestStressScoreTitle: "Stress Score Tertinggi",
    LowestStressScoreTitle: "Tingkat Score Terendah",
    DashboardGreeting: "Selamat pagi, ",
    LastJournalSummaryTitle: "Ringkasan Jurnal Terakhir",
    DetailJournalSummaryTitle: "Detail Jurnal Summary",
    DashboardNoActivityRecorded: "Belum ada aktivitas tercatat",
    DashboardDailyNoteTitle: "Catatan Harian",
    DashboardDailyNoteDescription: "Riwayat catatan dari jurnal aktivitas terakhir.",
    DashboardDailyNotePlaceholder: "Belum ada catatan aktivitas.",
    PositiveText: "Positif",
    SocialMediaTitle: "Media Sosial",
    StressScoreTitle: "Skor Stres",
    StressTrendTitle: "Tren stres 7 hari",
    AverageText: "Rata-rata",
    AcademicConditionTitle: "Kondisi Akademik",
    StudyTimeTitle: "Waktu Belajar",
    TaskLoadTitle: "Beban Tugas",
    LastNightSleepTitle: "Tidur (Semalam)",

    // Activity History Page
    ActivityHistoryTitle: "Riwayat Aktivitas",
    ActivityHistoryDescription: "Pantau riwayat jurnal harian yang telah Anda isi sebelumnya.",
    ActivityHistoryLoading: "Memuat riwayat aktivitas...",
    ActivityHistoryEmptyFiltered: "Belum ada riwayat aktivitas yang sesuai.",
    ActivityHistoryEmpty: "Belum ada riwayat aktivitas.",
    ActivityHistoryStatusAll: "Semua",
    ActivityHistoryStatusCompleted: "Selesai",
    ActivityHistoryStatusDraft: "Draft",
    ActivityHistoryStatusLate: "Terlambat",
    ActivityHistoryDateAll: "Semua data",
    ActivityHistoryDateLast7Days: "7 hari terakhir",
    ActivityHistoryDateThisMonth: "Bulan ini",
    ActivityHistoryDateLastMonth: "Bulan lalu",
    ActivityHistoryDateLast3Months: "3 bulan terakhir",
    ActivityHistorySortNewest: "Terbaru",
    ActivityHistorySortOldest: "Terlama",
    ActivityHistorySortHighestScore: "Skor tertinggi",
    ActivityHistorySortLowestScore: "Skor terendah",
    ActivityHistoryTableDate: "Tanggal",
    ActivityHistoryTableStressScore: "Skor Stres",
    ActivityHistoryTableStatus: "Status",
    ActivityHistoryTableAction: "Aksi",
    ActivityHistoryContinueWriting: "Lanjutkan Menulis",
    ActivityHistoryViewDetail: "Lihat Detail",
    ActivityHistoryScoreIncomplete: "Belum selesai",
    ActivityHistoryShowing: "Menampilkan",
    ActivityHistoryOf: "dari",
    ActivityHistoryActivity: "aktivitas",
    ActivityHistoryPrevious: "Sebelumnya",
    ActivityHistoryNext: "Berikutnya",

    // Insights Page
    AINarrativeInsightTitle: "Ringkasan Naratif AI",
    AINarrativeInsightSubtitle: "Berikut ringkasan untuk minggu ini",
    InsightsPageTitle: "Ringkasan",
    InsightsEyebrow: "Ringkasan & Analitik Akademik",
    InsightsHeroTitle: "Ringkasan Akademik & Lifestyle",
    InsightsLoading: "Memuat data ringkasan...",
    InsightsFetchError: "Gagal memuat data ringkasan.",
    InsightsLatestData: "Data terakhir",
    InsightsNoData: "Belum ada data",
    InsightsTrendUp: "naik",
    InsightsTrendDown: "turun",
    InsightsTrendStable: "stabil",
    InsightsAcademicAverageTitle: "Rata-Rata Kondisi Akademik",
    InsightsWeeklyActivityTitle: "Metrik Aktivitas Mingguan",
    InsightsStressIntensityTitle: "Intensitas Stres",
    InsightsStudyTimeLabel: "WAKTU BELAJAR",
    InsightsTaskLoadLabel: "BEBAN TUGAS",
    InsightsDeadlinePressureLabel: "TEKANAN DEADLINE",
    InsightsPhysicalActivityLabel: "AKTIVITAS FISIK",
    InsightsAverageSleepLabel: "TIDUR (RATA-RATA)",
    InsightsLatestFromDatabase: "Ringkasan terbaru dari database",
    InsightsFallbackWithData: "Dalam {count} catatan selesai terakhir pada rentang 7 hari ini, rata-rata stres berada di {stressScore}/100. Rata-rata tidur {sleepHours} jam, beban tugas {taskLoad}%, dan aktivitas fisik {physicalActivity} menit. Ringkasan akan diperbarui dari database setelah AI menyimpan data terbaru.",
    InsightsFallbackNoData: "Belum ada catatan aktivitas selesai untuk dianalisis. Isi jurnal harian terlebih dahulu agar ringkasan dan rekomendasi bisa diperbarui dari database.",
    InsightsNoPriorityToday: "Tidak ada rekomendasi.",
    InsightsNoLongTermSuggestions: "Tidak ada saran jangka panjang.",
    // prediksi stress
    PredictionPageTitle: "Prediksi Stres",
    PredictionTodayScoreLabel: "Skor Hari Ini",
    PredictionAverageLabel: "Rata-rata 7 Hari",
    PredictionLowestLabel: "Skor Terendah",
    PredictionHighestLabel: "Skor Tertinggi",
    PredictionTrendTitle: "Tren Prediksi 7 Hari",
    PredictionWeeklyAnalysisTitle: "Analisis Mingguan",
    PredictionWeeklyAnalysisDescription: "Lanjutan stres terdeteksi pada hari Sabtu dan Minggu. Pola ini menunjukkan bahwa kesehatan mental Anda sering terganggu dengan apakah evakuasi mingguan dan persiapan awal minggu.",
    PredictionModuleSuggestion: "Modifikasi Saran",
    PredictionHistoryTitle: "Riwayat Prediksi",
    PredictionHistoryTableDate: "Tanggal",
    PredictionHistoryTableScore: "Skor",
    PredictionHistoryTableLevel: "Level",
    PredictionHistoryTableActivity: "Aktivitas Terkait",
    PredictionExportPdf: "Export PDF",
    PredictionFilterData: "Filter Data",
    PredictionLastUpdate: "Pembaruan Terakhir",

    // Profile Pages
    AccountProfileLabel: "Profile Akun",
    EditPhotoButton: "Edit Foto",
    SavePhotoButton: "Simpan Foto",
    UnsavePhotoLabel: "Anda memiliki perubahan foto profil yang belum disimpan.",
    AccountInformationTitle: "Informasi Akun",
    AccountInformationDescription: "Kelola informasi profil dan data akun Anda.",

    FullNameLabel: "Nama Lengkap",
    EmailAddressLabel: "Alamat email",
    UpdateInformationButton: "Perbarui Informasi",
    UpdateFullNameTitle: "Perbarui Nama Lengkap",
    UpdateFullNameDescription: "Masukkan nama lengkap baru Anda.",
    UpdateSuccessMessage: "Nama berhasil disimpan.",
    SaveChangesButton: "Simpan",
    CancelButton: "Kembali",

    ChangePasswordTitle: "Ubah Password",
    CurrentPasswordLabel: "Password Saat Ini",
    NewPasswordLabel: "Password Baru",
    ConfirmPasswordLabel: "Konfirmasi Password",
    ResetPasswordButton: "Reset Password",
    CurrentPasswordPlaceholder: "Masukkan password saat ini",
    NewPasswordPlaceholder: "Masukkan password baru",
    ConfirmPasswordPlaceholder: "Konfirmasi password baru",
    PasswordRequiredError: "Semua kolom password wajib diisi.",
    PasswordMismatchError: "Password baru dan konfirmasi password tidak cocok.",
    PasswordMinLengthError: "Password baru minimal 6 karakter.",
    PasswordUpdateError: "Gagal memperbarui password.",
    PasswordSuccessTitle: "Password Berhasil Diubah",
    PasswordSuccessDescription: "Tekan di mana saja untuk login ulang.",
    BackToLoginButton: "Kembali ke Login",

  },


  en: {
     // General Translate
    Senin: "Mon",
    Selasa: "Tue",
    Rabu: "Wed",
    Kamis: "Thu",
    Jumat: "Fri",
    Sabtu: "Sat",
    Minggu: "Sun",
    // General
    HourText: "hours",
    LowText: "Low",
    MediumText: "Medium",
    HighText: "High",
    DeadlinePressureTitle: "Deadline Pressure",
    PhysicalActivityTitle: "Physical Activity",
    MoodScoreTitle: "Mood Score",
    FatigueLevelTitle: "Fatigue Level",
    NewInsight: "Recommendation for you",
    ModerateText: "Moderate", // Added for stress_level translation
    CloseButton: "Close",
    DashboardDateLocale: "en-US",
    MinuteText: "Min",
    PriorityTodayTitle: "Recommendations",
    LongTermTitle: "Long-term Suggestions",

    // LeftPanel
    Heading1: "AI-Based Stress Level Analysis",
    Heading2: "For Your Mental Health.",
    Deskripsi: "Monitor your mental state through real-time evaluation of daily activities and habits using Artificial Intelligence technology.",
    Subheading1: "Daily Stress Check",
    Subdeskripsi1: "AI analyzes daily questionnaire responses to quickly and accurately estimate stress levels.",
    Subheading2: "Personal Reports & Insights",
    Subdeskripsi2: "Get a summary of stress conditions and daily recommendations to help maintain your mental health.",

    //Register Pages
    Create: "Create Account",
    Form: "Please complete the form below.",
    LabelName: "Full Name",
    InputName: "Enter Your Name",
    InputEmail: "Enter Your Email",
    LabelPassword: "Password",
    LabelConfirmPassword: "Confirm Password",
    SubmitRegister: "Register Now",
    LabelLogin: "Already Have an Account?",
    LinkLogin: "Login here",
    Google: "Continue With Google",

    // Login Pages
    Login: "Login",
    LabelRegister: "Don't have an account?",
    LinkRegister: "Register",
    SubmitLogin: "Login Now",
    ResetPassword: "Forgot Password",

    // Reset Password Pages
    HeadingResetPassword: "Forgot Password?",
    DeskripsiResetPassword: "Enter your registered email to receive password reset instructions.",
    ButtonResetPassword: "Send Recovery Link",
    BackToLogin: "Return to Login",

    // New Password Pages
    HeadingNewPassword: "Create New Password",
    DeskripsiNewPassword: "Please enter a new password for your account.",
    ButtonNewPassword: "Update Password",
    LabelNewPassword: "New Password",
    LabelConfirmNewPassword: "Confirm New Password",

    // Sidebar
    ActSdbr: "Activity History",
    CekStresSdbr: "Summary",
    ReqomendationSdbr: "Recommendation",
    ProfileSdbr: "My Profile",
    StressCheck: "Stress Check",
    LogoutSdbr: "Logout",

    // Catat Aktivitas Pages
    ActivitySaveDraftButton: "Save Draft",
    LogActivityTitle: "Log Activity Data",
    ActivityPageTitle: "Input Activity Data",
    ActivityPageDescription: "Complete the data below for a deeper stress-level analysis from our AI system.",
    ActivityDailySectionTitle: "Daily Activities",
    ActivityDailySectionDescription: "Complete your activity data to get a more accurate stress prediction.",
    ActivityDigitalSectionTitle: "Digital Activities",
    ActivityDigitalSectionDescription: "Record your screen time and social media usage duration.",
    ActivityConditionSectionTitle: "Academic & Personal Condition",
    ActivityConditionSectionDescription: "Adjust each slider based on your condition yesterday.",
    ActivityDateTitle: "Activity Date",
    ActivitySleepHoursTitle: "Sleep Hours",
    ActivitySleepPlaceholder: "Example: 7.5",
    ActivitySleepDescription: "Total sleep hours last night",
    ActivityPhysicalActivityPlaceholder: "Minutes",
    ActivityPhysicalDescription: "Physical activity duration",
    ActivityStudyHoursTitle: "Study Hours",
    ActivityStudyDescription: "Total study time outside class",
    ActivityScreenTimeTitle: "Screen Time (Hours)",
    ActivityScreenTimeDescription: "Total screen time outside study needs",
    ActivitySocialMediaTitle: "Social Media Usage (Hours)",
    ActivitySocialMediaDescription: "Time spent on social media (Instagram, TikTok, X, etc.)",
    ActivityAssignmentLoadTitle: "Assignment Load",
    ActivityAssignmentDescription: "How heavy is your assignment load?",
    ActivityDeadlineDescription: "How urgent are the deadlines you are facing?",
    ActivityFatigueDescription: "How physically and mentally tired do you feel?",
    ActivityMoodDescription: "How is your overall mood?",
    ActivitySelectDateLabel: "Select Activity Date",
    ActivitySubmitConfirmationTitle: "Submit activity data?",
    ActivitySubmitConfirmationDescription: "Are you sure you want to submit activity data for",
    ActivityReviewAgainButton: "Review again",
    ActivityConfirmSubmitButton: "Yes, submit",
    ActivityAllDatesFilledTitle: "All dates are filled",
    ActivityAllDatesFilledDescription: "The four activity dates before today already have records. You will be redirected to the dashboard.",
    ActivityGoToDashboardButton: "Go to Dashboard",
    ActivityDateRequiredError: "Select an activity date first.",
    ActivityMinimumInputError: "Fill in at least one activity field before saving and predicting.",
    ActivityAnalysisLoadingTitle: "Waiting for AI analysis result...",
    ActivityAnalysisLoadingDescription: "The stress score will appear after the AI model saves the prediction result.",
    ActivityHoursSuffix: "HOURS",
    ActivityMinutesSuffix: "MIN",
    ActivityLowLabel: "Low",
    ActivityExtremeLabel: "Extreme",
    ActivityRelaxedLabel: "Relaxed",
    ActivityUrgentLabel: "Urgent",
    ActivityFreshLabel: "Fresh",
    ActivityExhaustedLabel: "Fully Exhausted",
    ActivityBadLabel: "Bad",
    ActivityVeryGoodLabel: "Very Good",
    ActivityQuiteHighStatus: "Quite High",
    ActivityBadgeGood: "Good",
    ActivityBadgeLow: "Low",
    ActivityBadgeMedium: "Medium",
    ActivityBadgeQuiteHigh: "Quite High",
    ActivityBadgeVeryGood: "Very Good",
    ActivityBadgeVeryHigh: "Very High",
    ActivityDailyNoteTitle: "Daily Note",
    ActivityDailyNoteDescription: "Briefly describe how your day went yesterday.",
    ActivityDailyNotePlaceholder: "Example: Today I felt quite tired because tasks piled up, I slept less, and it was hard to focus while studying.",
    ActivitySubmitButton: "Save & Predict",
    ActivitySubmittingButton: "Saving...",
    ActivityDraftSavedMessage: "Draft saved successfully.",
    ActivitySuccessMessage: "Activity submitted successfully.",
    ActivitySubmitErrorMessage: "An error occurred while submitting data.",
    ActivityJournalHeader: "Journal Entry for Activity Date",
    ActivityJournalDescription: "This data will be used to predict stress score, generate insights, and recommendations.",
    ActivityReviewLabel: "Analysis Preview",
    ActivityTodayStatusTitle: "Today's Status",
    ActivityAnalysisTag: "Analysis",
    ActivityStressRiskHigh: "High Stress Risk",
    ActivityGoToSummaryButton: "Go to Summary",
    ActivityCloseButton: "Close",

    // Dashboard Page
    DashboardGreeting: "Good Morning, ",
    LastJournalSummaryTitle: "Latest Journal Summary",
    DetailJournalSummaryTitle: "Journal Summary Detail",
    DashboardNoActivityRecorded: "No activity recorded yet",
    DashboardDailyNoteTitle: "Daily Note",
    DashboardDailyNoteDescription: "History note from the latest activity journal.",
    DashboardDailyNotePlaceholder: "No activity note yet.",
    PositiveText: "Positive",
    SocialMediaTitle: "Social Media",
    StressScoreTitle: "Stress Score",
    HighestStressScoreTitle: "Highest Stress Score",
    LowestStressScoreTitle: "Lowest Stress Score",
    StressTrendTitle: "7-Day Stress Trend",
    AverageText: "Average",
    AcademicConditionTitle: "Academic Condition",
    StudyTimeTitle: "Study Time",
    TaskLoadTitle: "Task Load",
    LastNightSleepTitle: "Sleep (Last Night)",

    // Activity History Page
    ActivityHistoryTitle: "Activity History",
    ActivityHistoryDescription: "Monitor the daily journal history you have submitted before.",
    ActivityHistoryLoading: "Loading activity history...",
    ActivityHistoryEmptyFiltered: "No matching activity history yet.",
    ActivityHistoryEmpty: "No activity history yet.",
    ActivityHistoryStatusAll: "All",
    ActivityHistoryStatusCompleted: "Completed",
    ActivityHistoryStatusDraft: "Draft",
    ActivityHistoryStatusLate: "Late",
    ActivityHistoryDateAll: "All data",
    ActivityHistoryDateLast7Days: "Last 7 days",
    ActivityHistoryDateThisMonth: "This month",
    ActivityHistoryDateLastMonth: "Last month",
    ActivityHistoryDateLast3Months: "Last 3 months",
    ActivityHistorySortNewest: "Newest",
    ActivityHistorySortOldest: "Oldest",
    ActivityHistorySortHighestScore: "Highest score",
    ActivityHistorySortLowestScore: "Lowest score",
    ActivityHistoryTableDate: "Date",
    ActivityHistoryTableStressScore: "Stress Score",
    ActivityHistoryTableStatus: "Status",
    ActivityHistoryTableAction: "Action",
    ActivityHistoryContinueWriting: "Continue Writing",
    ActivityHistoryViewDetail: "View Detail",
    ActivityHistoryScoreIncomplete: "Incomplete",
    ActivityHistoryShowing: "Showing",
    ActivityHistoryOf: "of",
    ActivityHistoryActivity: "activities",
    ActivityHistoryPrevious: "Previous",
    ActivityHistoryNext: "Next",
   
    // Insights Page
    AINarrativeInsightTitle: "AI Narrative Summary",
    AINarrativeInsightSubtitle: "Here are summaries for this week",
    InsightsPageTitle: "Summary",
    InsightsEyebrow: "Summary & Academic Analytics",
    InsightsHeroTitle: "Academic & Lifestyle Summary",
    InsightsLoading: "Loading summary data...",
    InsightsFetchError: "Failed to load summary data.",
    InsightsLatestData: "Latest data",
    InsightsNoData: "No data yet",
    InsightsTrendUp: "up",
    InsightsTrendDown: "down",
    InsightsTrendStable: "stable",
    InsightsAcademicAverageTitle: "Average Academic Condition",
    InsightsWeeklyActivityTitle: "Weekly Activity Metrics",
    InsightsStressIntensityTitle: "Stress Intensity",
    InsightsStudyTimeLabel: "STUDY TIME",
    InsightsTaskLoadLabel: "TASK LOAD",
    InsightsDeadlinePressureLabel: "DEADLINE PRESSURE",
    InsightsPhysicalActivityLabel: "PHYSICAL ACTIVITY",
    InsightsAverageSleepLabel: "SLEEP (AVERAGE)",
    InsightsLatestFromDatabase: "Latest summary from database",
    InsightsFallbackWithData: "Across the last {count} completed records in this 7-day range, average stress is {stressScore}/100. Average sleep is {sleepHours} hours, task load is {taskLoad}%, and physical activity is {physicalActivity} minutes. Summary will update from the database after AI saves the latest data.",
    InsightsFallbackNoData: "No completed activity records are available for analysis yet. Fill in your daily journal first so summary and recommendations can be updated from the database.",
    InsightsNoPriorityToday: "No recommendations.",
    InsightsNoLongTermSuggestions: "No long-term suggestions yet.",
    // prediksi stress
    PredictionPageTitle: "Stress Prediction",
    PredictionTodayScoreLabel: "Today's Score",
    PredictionAverageLabel: "7-Day Average",
    PredictionLowestLabel: "Lowest Score",
    PredictionHighestLabel: "Highest Score",
    PredictionTrendTitle: "7-Day Prediction Trend",
    PredictionWeeklyAnalysisTitle: "Weekly Analysis",
    PredictionWeeklyAnalysisDescription: "Continued stress detected on Saturday and Sunday. This pattern shows that your mental health is often disrupted by weekly evaluations and early week preparations.",
    PredictionModuleSuggestion: "Modify Suggestions",
    PredictionHistoryTitle: "Prediction History",
    PredictionHistoryTableDate: "Date",
    PredictionHistoryTableScore: "Score",
    PredictionHistoryTableLevel: "Level",
    PredictionHistoryTableActivity: "Related Activity",
    PredictionExportPdf: "Export PDF",
    PredictionFilterData: "Filter Data",
    PredictionLastUpdate: "Last Update",

    // Profile Pages
    AccountProfileLabel: "Account Profile",
    EditPhotoButton: "Edit Photo",
    SavePhotoButton: "Save Photo",
    UnsavePhotoLabel: "You have unsaved profile photo changes.",

    AccountInformationTitle: "Account Information",
    AccountInformationDescription: "Manage your profile information and account data.",
    FullNameLabel: "Full Name",
    EmailAddressLabel: "Email Address",
    UpdateInformationButton: "Update Information",
    UpdateFullNameTitle: "Update Full Name",
    UpdateFullNameDescription: "Enter your new full name.",
    UpdateSuccessMessage: "Name saved successfully.",
    SaveChangesButton: "Save",
    CancelButton: "Back",
    AccountStatisticsTitle: "Account Statistics",
    TotalAnalysisEntriesTitle: "Total Analysis Entries",
    AverageStressScoreTitle: "Average Stress Score",
    OptimalClinicalRangeText: "Optimal clinical range detected",
    ActiveStreakTitle: "Active Streak",
    ChangePasswordTitle: "Change Password",
    CurrentPasswordLabel: "Current Password",
    NewPasswordLabel: "New Password",
    ConfirmPasswordLabel: "Confirm Password",
    ResetPasswordButton: "Reset Password",
    CurrentPasswordPlaceholder: "Enter your current password",
    NewPasswordPlaceholder: "Enter your new password",
    ConfirmPasswordPlaceholder: "Confirm your new password",
    PasswordRequiredError: "All password fields are required.",
    PasswordMismatchError: "New password and confirmation password do not match.",
    PasswordMinLengthError: "New password must be at least 6 characters.",
    PasswordUpdateError: "Failed to update password.",
    PasswordSuccessTitle: "Password Changed Successfully",
    PasswordSuccessDescription: "Tap anywhere to log in again.",
    BackToLoginButton: "Back to Login",
    DangerZoneTitle: "Danger Zone",
    DangerZoneDescription: "Deactivating your account will permanently delete all clinical stress history and data insights.",
    DeactivateAccountButton: "Deactivate Account",

  },
};

function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'id';
  });

  function toggleLanguage() {
    setLanguage((prev) => {
      const next = prev === 'id' ? 'en' : 'id';
      localStorage.setItem('language', next);
      return next;
    });
  }

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

function useLanguage() {
  return useContext(LanguageContext);
}

// eslint-disable-next-line react-refresh/only-export-components
export { LanguageContext, LanguageProvider, useLanguage };
